"use client";
import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabase";
export default function Grupo({params}:{params:{token:string}}){
 const[d,setD]=useState<any>(null),[e,setE]=useState(""),[id,setId]=useState(""),[authorized,setAuthorized]=useState(false);
 useEffect(()=>{(async()=>{const{data,error}=await supabase.from("group_links").select("id,group_id,program_id,share_token,active,groups(id,name,quantity,quantity_label,responsible_name,responsible_whatsapp),programs(id,date,start_time,end_time,status),parks(name,logo_url,primary_color)").eq("share_token",params.token).eq("active",true).maybeSingle();if(error||!data){setE("Link inválido ou expirado.");return}setD(data)})()},[params.token]);
 async function enter(){setE("");const{data:fr}=await supabase.from("freelancers").select("id,system_id,name,label").eq("system_id",id.trim().toUpperCase()).eq("status","active").maybeSingle();if(!fr){setE("ID inválido.");return}const{data:assignment}=await supabase.from("group_freelancers").select("id").eq("group_id",d.group_id).eq("freelancer_id",fr.id).maybeSingle();if(!assignment){setE("Este freelancer não está autorizado neste grupo.");return}setAuthorized(true);}
 if(e&&!d)return <main className="dashboard"><section className="dash-hero"><h1>{e}</h1></section></main>;
 if(!d)return <main className="dashboard"><section className="dash-hero"><h1>Carregando grupo...</h1></section></main>;
 return <main className="dashboard"><header className="dash-header"><div className="auth-brand"><span className="brand-mark">L</span><span><b>LOSI</b> ESCALA</span></div><span>{d.parks?.name||"SEU PARQUE"}</span></header><section className="dash-hero"><div><span className="eyebrow-text">GRUPO</span><h1>{d.groups?.name}</h1><p>{d.groups?.quantity} {d.groups?.quantity_label||"participantes"}</p><p>{d.groups?.responsible_name||"Responsável não informado"}</p></div></section><section className="scales-content"><article className="scale-card"><h2>Acesso da equipe</h2><p>Informe seu ID para ver a programação deste grupo.</p><input placeholder="Ex.: COL-12345" value={id} onChange={x=>setId(x.target.value)}/><button className="button" onClick={enter}>Entrar</button>{e&&<small>{e}</small>}{authorized&&<div style={{marginTop:20}}><h2>Programação</h2><p>{d.programs?.status==="published"?d.programs?.date+" · "+d.programs?.start_time?.slice(0,5)+" — "+d.programs?.end_time?.slice(0,5):"Programação ainda não publicada."}</p><p>Acesso autorizado para este grupo.</p></div>}</article></section></main>
}