"use client";
import Link from"next/link";import{useEffect,useState}from"react";import{supabase}from"@/lib/supabase";
type ScaleDetailProps={params:Promise<{id:string}>};
export default function EscalaDetalhe({params}:ScaleDetailProps){const[s,setS]=useState<any>(),[people,setPeople]=useState<any[]>([]),[msg,setMsg]=useState("");
const[scaleId,setScaleId]=useState("");
useEffect(()=>{void params.then(({id})=>setScaleId(id))},[params]);
async function load(id:string){const{data}=await supabase.from("scales").select("*").eq("id",id).maybeSingle();setS(data);if(data){const{data:p}=await supabase.from("scale_freelancers").select("id,status,freelancer_id,freelancers(name,system_id,whatsapp,label)").eq("scale_id",id);setPeople(p||[])}}useEffect(()=>{if(scaleId)void load(scaleId)},[scaleId]);
async function remove(id:string){const{error}=await supabase.from("scale_freelancers").update({status:"removed"}).eq("id",id);setMsg(error?"Não foi possível remover.":"Freelancer removido da escala.");if(!error)void load(scaleId)}
if(!s)return <main className="dashboard"><section className="dash-hero"><h1>Carregando escala...</h1></section></main>;
return <main className="dashboard"><header className="dash-header"><Link href="/painel" className="auth-brand"><span className="brand-mark">L</span><span><b>LOSI</b> ESCALA</span></Link><nav className="dash-nav"><Link href="/painel/escalas" className="active">Escalas</Link><Link href="/painel/freelancers">Freelancers</Link><Link href="/painel/grupos">Grupos</Link></nav></header><section className="dash-hero"><div><span className="eyebrow-text">ESCALA · {s.status}</span><h1>{s.date}<br/><span>{s.start_time.slice(0,5)} — {s.end_time.slice(0,5)}</span></h1><p>{s.notes||"Sem observações."}</p></div><Link className="button" href={`/escala/${s.share_token}`}>Abrir link público ↗</Link></section>{msg&&<div className="scales-error">{msg}</div>}<section className="scales-content"><div className="scale-summary"><div><span>CAPACIDADE</span><strong>{s.max_freelancers}</strong></div><div><span>PARTICIPANTES</span><strong>{people.filter(x=>x.status==="confirmed"||x.status==="available").length}</strong></div><div><span>STATUS</span><strong>{s.status}</strong></div></div><div className="scale-list">{people.length===0?<div className="scale-empty"><strong>Nenhum freelancer confirmado.</strong><span>Compartilhe o link da escala para sua equipe.</span></div>:people.map(x=><article className="scale-card" key={x.id}><div className="scale-date"><span>{x.status}</span><strong>{(x.freelancers?.label||"COL").slice(0,3).toUpperCase()}</strong><small>{x.freelancers?.system_id||"—"}</small></div><div className="scale-main"><h2>{x.freelancers?.name||"Freelancer"}</h2><p>{x.freelancers?.whatsapp||"WhatsApp não informado"}</p></div><div className="scale-actions">{x.status!=="removed"&&<button onClick={()=>remove(x.id)}>Remover da escala</button>}</div></article>)}</div></section></main>}