"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { supabase } from "@/lib/supabase";
type F={id:string;name:string;label:string;whatsapp:string|null;system_id:string;status:string};
export default function Freelancers(){
 const [rows,setRows]=useState<F[]>([]),[parkId,setParkId]=useState(""),[name,setName]=useState(""),[whatsapp,setWhatsapp]=useState(""),[label,setLabel]=useState("Freelancer"),[saving,setSaving]=useState(false),[error,setError]=useState("");
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:m}=await supabase.from("park_users").select("park_id").eq("id",user.id).maybeSingle();if(!m)return;setParkId(m.park_id);const {data}=await supabase.from("freelancers").select("id,name,label,whatsapp,system_id,status").eq("park_id",m.park_id).order("name");setRows(data||[])})()},[]);
 async function add(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");const {data:fid,error:fe}=await supabase.rpc("generate_freelancer_id",{p_park_id:parkId});if(fe){setError("Não foi possível gerar o ID.");setSaving(false);return}const {data,error:ie}=await supabase.from("freelancers").insert({park_id:parkId,name:name.trim(),label,whatsapp:whatsapp.trim()||null,system_id:fid}).select("id,name,label,whatsapp,system_id,status").single();if(ie||!data){setError("Não foi possível cadastrar o freelancer.");setSaving(false);return}setRows(v=>[...v,data]);setName("");setWhatsapp("");setSaving(false)}
 return <main className="dashboard"><header className="dash-header"><Link href="/painel" className="auth-brand"><span className="brand-mark">L</span><span><b>LOSI</b> ESCALA</span></Link><nav className="dash-nav"><Link href="/painel">Visão geral</Link><Link href="/painel/escalas">Escalas</Link><Link className="active" href="/painel/freelancers">Freelancers</Link><Link href="/painel/grupos">Grupos</Link><Link href="/painel/programacoes">Programações</Link></nav><div className="dash-user"><span>SEU PARQUE</span><b>Gestor</b></div></header><section className="dash-hero"><div><span className="eyebrow-text">EQUIPE</span><h1>Freelancers.<br/><span>Quem faz a operação.</span></h1><p>Cadastre a equipe, gere um ID permanente e mantenha o histórico organizado.</p></div></section><section className="scales-content"><form className="inline-create" onSubmit={add}><input required placeholder="Nome do freelancer" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="WhatsApp" value={whatsapp} onChange={e=>setWhatsapp(e.target.value)}/><select value={label} onChange={e=>setLabel(e.target.value)}><option>Freelancer</option><option>Monitor</option><option>Recreador</option><option>Colaborador</option><option>Professor</option><option>Guia</option></select><button className="button" disabled={saving}>{saving?"Cadastrando...":"+ Adicionar"}</button></form>{error&&<div className="scales-error">{error}</div>}<div className="scale-list">{rows.map(f=><article className="scale-card" key={f.id}><div className="scale-date"><span>ID</span><strong>{f.system_id.replace("COL-","")}</strong><small>{f.status}</small></div><div className="scale-main"><div className="scale-title-row"><div><span className="scale-id">{f.label}</span><h2>{f.name}</h2></div><span className="scale-status scale-status-open">{f.status==="active"?"Ativo":f.status}</span></div><p>{f.whatsapp||"WhatsApp não informado."}</p></div></article>)}</div></section></main>;
}