"use client";
import Link from"next/link";
import{useEffect,useMemo,useState}from"react";
import{supabase}from"@/lib/supabase";
export default function Operacao(){
 const[rows,setRows]=useState<any[]>([]),[park,setPark]=useState("SEU PARQUE"),[msg,setMsg]=useState(""),[tick,setTick]=useState(Date.now());
 useEffect(()=>{let timer:any;async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){setMsg("Faça login para acessar a operação.");return}const{data:pu}=await supabase.from("park_users").select("park_id").eq("id",user.id).maybeSingle();if(!pu?.park_id){setMsg("Acesso não autorizado.");return}const[pk,live]=await Promise.all([supabase.from("parks").select("name").eq("id",pu.park_id).maybeSingle(),supabase.from("live_program_operation").select("*").eq("park_id",pu.park_id).eq("program_status","published").order("starts_at")]);setPark(pk.data?.name||"SEU PARQUE");if(live.error){setMsg("Não foi possível carregar a operação.");return}setRows(live.data||[]);setTick(Date.now())}void load();timer=setInterval(()=>{void load()},30000);return()=>clearInterval(timer)},[]);
 const groups=useMemo(()=>Array.from(new Map(rows.map(r=>[r.group_id,r])).values()),[rows,tick]);
 const state=(r:any)=>{const n=Date.now(),s=new Date(r.starts_at).getTime(),e=new Date(r.ends_at).getTime();return s<=n&&e>n?"now":s>n?"next":"done"};
 return <main className="dashboard"><header className="dash-header"><Link href="/painel" className="auth-brand"><span className="brand-mark">L</span><span><b>LOSI</b> ESCALA</span></Link><nav className="dash-nav"><Link href="/painel">Visão geral</Link><Link href="/painel/operacao" className="active">Operação</Link><Link href="/painel/programacoes">Programações</Link></nav></header><section className="dash-hero"><div><span className="eyebrow-text">OPERAÇÃO · AO VIVO</span><h1>{park}</h1><p>Acompanhe o agora, o próximo passo e os grupos em operação.</p></div></section>{msg?<div className="scales-error">{msg}</div>:<section className="scales-content"><div className="scale-list">{groups.map((g:any)=>{const current=rows.find(r=>r.group_id===g.group_id&&state(r)==="now"),next=rows.find(r=>r.group_id===g.group_id&&state(r)==="next");return <article className="scale-card" key={g.group_id}><div className="scale-date"><span>GRUPO</span><strong>{g.group_name}</strong></div><div className="scale-main"><h2>{current?current.activity_name:"Nenhuma atividade agora"}</h2><p>{current?"AGORA · "+new Date(current.starts_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})+" — "+new Date(current.ends_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"}):"Fora de atividade"}</p><p>{current?.location||"—"}</p>{next&&<p><strong>PRÓXIMO:</strong> {next.activity_name+" · "+new Date(next.starts_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})+" · "+(next.location||"—")}</p>}</div></article>})}</div></section>}</main>
}